import type { FinanceData } from "./model";
const today = new Date();
const month = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}`;
const day = (number: number) => `${month}-${String(number).padStart(2, "0")}`;
export const demoData: FinanceData = {
  accounts: [
    {
      id: "demo-nubank",
      name: "Nubank",
      institution: "Nubank",
      kind: "checking",
      openingBalanceCents: 204537,
      color: "#8b5cf6",
      active: true,
    },
    {
      id: "demo-bb",
      name: "Banco do Brasil",
      institution: "Banco do Brasil",
      kind: "checking",
      openingBalanceCents: 249000,
      color: "#e3b341",
      active: true,
    },
  ],
  benefits: [
    {
      id: "demo-va",
      name: "Vale Alimentação",
      company: "Pluxee",
      kind: "va",
      openingBalanceCents: 64643,
      monthlyCreditCents: 65000,
      creditDay: 5,
      active: true,
    },
    {
      id: "demo-vr",
      name: "Vale Refeição",
      company: "Alelo",
      kind: "vr",
      openingBalanceCents: 31200,
      monthlyCreditCents: 40000,
      creditDay: 5,
      active: true,
    },
  ],
  transactions: [
    {
      id: "demo-1",
      description: "Salário",
      amountCents: 230000,
      type: "income",
      date: day(5),
      category: "Salário",
      accountId: "demo-nubank",
      benefitId: null,
      createdAt: day(5),
    },
    {
      id: "demo-2",
      description: "Supermercado",
      amountCents: 12643,
      type: "expense",
      date: day(8),
      category: "Alimentação",
      accountId: null,
      benefitId: "demo-va",
      createdAt: day(8),
    },
    {
      id: "demo-3",
      description: "Combustível",
      amountCents: 20000,
      type: "expense",
      date: day(11),
      category: "Automóvel",
      accountId: "demo-nubank",
      benefitId: null,
      createdAt: day(11),
    },
    {
      id: "demo-4",
      description: "Netflix",
      amountCents: 4490,
      type: "expense",
      date: day(15),
      category: "Assinaturas",
      accountId: "demo-nubank",
      benefitId: null,
      createdAt: day(15),
    },
    {
      id: "demo-5",
      description: "Restaurante",
      amountCents: 5200,
      type: "expense",
      date: day(18),
      category: "Alimentação",
      accountId: null,
      benefitId: "demo-vr",
      createdAt: day(18),
    },
  ],
};
